import 'dart:math';
import 'package:get/get.dart';

class LinkedChild {
  final String id;
  final String name;
  final String email;
  final bool isOnline;
  final int alertsToday;
  final DateTime linkedAt;

  LinkedChild({
    required this.id,
    required this.name,
    required this.email,
    required this.isOnline,
    required this.alertsToday,
    required this.linkedAt,
  });
}

class LinkController extends GetxController {
  // Observable
  // Pairing Code (Generated by Parent)
  final RxString pairingCode = ''.obs;

  // Child side state
  final RxBool isParentModeActive = false.obs; // If linked to parent

  // Parent side state
  final RxList<LinkedChild> linkedChildren = <LinkedChild>[].obs;

  @override
  void onInit() {
    super.onInit();
    _loadMockData();
  }

  void _loadMockData() {
    // Parent sees these children
    linkedChildren.value = [
      LinkedChild(
        id: 'child_1',
        name: 'Budi Santoso',
        email: 'budi@demo.com',
        isOnline: true,
        alertsToday: 2,
        linkedAt: DateTime.now().subtract(const Duration(days: 7)),
      ),
      LinkedChild(
        id: 'child_2',
        name: 'Siti Nurhaliza',
        email: 'siti@demo.com',
        isOnline: false,
        alertsToday: 0,
        linkedAt: DateTime.now().subtract(const Duration(days: 3)),
      ),
    ];
  }

  // --- PARENT METHODS (Generate Code) ---

  // Generate Pairing Code for Parent to show to Child
  void generatePairingCode() {
    final random = Random();
    String code = '';
    for (int i = 0; i < 6; i++) {
      code += random.nextInt(10).toString();
    }
    pairingCode.value = code;
  }

  // Helper to ensure we have a code
  String getOrGenerateCode() {
    if (pairingCode.value.isEmpty) {
      generatePairingCode();
    }
    return pairingCode.value;
  }

  // --- CHILD METHODS (Input Code) ---

  // Child inputs code to link to parent
  Future<bool> joinParent(String inputCode) async {
    // Mock API call
    await Future.delayed(const Duration(seconds: 1));

    // Mock Validation: Accept any 6 digit code
    if (inputCode.length == 6) {
      isParentModeActive.value = true;
      return true;
    }
    return false;
  }

  // Disconnect child (Parent side)
  void disconnectChild(String childId) {
    linkedChildren.removeWhere((child) => child.id == childId);
  }

  // Format code for display (XXX-XXX)
  String formatCode(String code) {
    if (code.length == 6) {
      return '${code.substring(0, 3)}-${code.substring(3, 6)}';
    }
    return code;
  }
}
